ALTER TABLE "Salon" ADD COLUMN IF NOT EXISTS "notificationChannel" TEXT NOT NULL DEFAULT 'EMAIL';
ALTER TABLE "Salon" ADD COLUMN IF NOT EXISTS "notificationFrequency" TEXT NOT NULL DEFAULT 'IMMEDIATE';
ALTER TABLE "Salon" ADD COLUMN IF NOT EXISTS "notificationEmail" TEXT;
ALTER TABLE "Salon" ADD COLUMN IF NOT EXISTS "notificationPhone" TEXT;
